name: flutter_nps
description: A new Flutter module project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  intl: any


dev_dependencies:
   flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  generate: true

  module:
    androidX: true
    androidPackage: com.example.flutter_nps
    iosBundleIdentifier: com.example.flutterNps
